PAPER = paper
TEX = $(wildcard *.tex)
BIB = biblio.bib
FIGS = $(wildcard figures/*.pdf figures/*.png graphs/*.pdf graphs/*.png)

LATEX = pdflatex -interaction=nonstopmode

.PHONY: clean

$(PAPER).pdf: $(TEX) $(BIB) $(FIGS) jpaper.cls
	$(LATEX) $(PAPER)
	bibtex $(PAPER)
	$(LATEX) $(PAPER)
	$(LATEX) $(PAPER)

clean:
	rm -f *.aux *.bbl *.blg *.log *.nav *.out *.snm *.toc $(PAPER).pdf

